### ISSUE TITLE
Chrome update breaks functionality?

### ISSUE THREAD

**Issue by CaptainCredible** [nkymut/microbit-webusb-p5js#3]
I have had this and other solutions to webUSB with microbit working until very recently, did a recent chrome update break this?
I cannot get any of the exampes posted to work. And my own guitar hero clone also stopped working: https://www.captaincredible.com/MBOH/

**Comment by nkymut** [comment]
We have confirmed that the latest micro:bit v2.2 is causing an issue with WebUSB communication on both Mac and Windows.
It might be related with the interface processor change but still what is the core issue. 

https://support.microbit.org/support/solutions/articles/19000132336-bbc-micro-bit-v2-interface-processor-change-v2-2-

What version of micro:bit and Chrome are you using?

**Comment by CaptainCredible** [comment]
Sorry for jumping to conclusions, upon further investigating I was beginning to suspect that this new box of v2.21 micro:bits was the culprit. I also tried changing the firmware to no avail. Curiously though the speeds are fine in the makecode editor

**Comment by nkymut** [comment]
#4
